### ISSUE TITLE
[Feature] Pass font root directory instead of individual font folders

### ISSUE THREAD

**Issue by LordFlashmeow** [moi15moi/FontCollector#29]
I have a root font folder that contains folders for each font family.

The `--additional-fonts` option isn't recursive, so I have to pass a list of all the font family folders on the command line.

It would be very helpful if there was a `--font-root` argument that would recursively search one (or more) folders for font files.

**Comment by moi15moi** [comment]
Close with #30 
Like said, the feature will be available in 3.0.0
