### ISSUE TITLE
Fonts activated by FontBase are not found by FontCollector

### ISSUE THREAD

**Issue by yuv420p10le** [moi15moi/FontCollector#40]
(Windows 11)

The current font enumeration method does not find fonts activated by [FontBase](https://fontba.se/); even though they should be detected as system fonts considering every app with a font picker can find them.

Potentially could also be causing issues with other apps that utilize the same method as FontBase to activate their fonts.

I've confirmed with other users that they also experience the same issue. One user have testified that FontCollector successfully finds their FontBase fonts though but we couldn't identify the cause—so there might be a configuration change necessary for it to work.

**Comment by moi15moi** [comment]
This is a issue for: https://github.com/moi15moi/FindSystemFontsFilename

**Comment by moi15moi** [comment]
Could you tell me if this print Found... ?

```py
from find_system_fonts_filename import get_system_fonts_filename

fonts = get_system_fonts_filename()
font_name = "Comixo" # Replace this by the family name you activated

for font in fonts:
    if font_name.lower() in font.lower():
        print(f"Found at {font}")
```

**Comment by yuv420p10le** [comment]
Thanks for replying.

It doesn't reach the `print` statement. Works if I replace it with a different font that was manually installed however; not ones from FontBase.

**Comment by moi15moi** [comment]
Ok, then, this is a issue for https://github.com/moi15moi/FindSystemFontsFilename
Please, reopen the issue on the right repo.
