### ISSUE TITLE
Specific font causing error when collecting fonts on Windows

### ISSUE THREAD

**Issue by asakurato** [moi15moi/FontCollector#44]
When running the script with a command:
`fontCollector -i "test.ass"`, I get the following error:
`ERROR - An unknown error occurred while reading the font "C:\USERS\BEGIJ\FONTBASE\FONTS\MY COLLECTION\BOXED_IN1.TTF"`.
If I remove this specific font, script finishes successfully. I'm on Windows 11 and using 3.0.0c1 of Fontcollector. 
I'm attaching this font and test file as a google drive link
[Ass and Font](https://drive.google.com/file/d/1aY1c47ydHfrqx96Qd5lVN30kX7gu35xw/view?usp=sharing)

**Comment by moi15moi** [comment]
A new pre-release version have been published here which resolve this bug: https://pypi.org/project/FontCollector/3.0.0rc2/
