### ISSUE TITLE
ASS style fonts are not collected if they're unused

### ISSUE THREAD

**Issue by yuv420p10le** [moi15moi/FontCollector#46]
`AssDocument::get_used_style(true)` does not return `Arial` in this case.  `__set_used_styles` gets called for `Arial`, but it's not being set as a used style.

```ass
[Script Info]
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
Video Aspect Ratio: c1.777780

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Sign,Arial,30,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,15,15,15,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.10,0:00:10.10,Sign,,0,0,0,,{\pos(1118.334,292.5)\fay-0.6\fnAdobe Gothic Std B\fs15\b1\c&H574942&\blur0.75}Oozuka
```

The only font collected here is `Adobe Gothic Std B`; so `Arial` does not end up being muxed into the final output when used in a muxing script.

Playing with mpv and without a font provider, using only the fonts collected by fontcollector, this appears:
```
mpv --no-config --sub-font-provider=none <path to mkv>
[sub/ass] fontselect: failed to find any fallback with glyph 0x0 for font: (Arial, 400, 0)
```

**Comment by moi15moi** [comment]
Thanks for opening an issue!
Actually, in this case, you need to ignore the error printed by libass since Arial isn't displayed. If a font isn't displayed, you don't need it even if libass print an error.

I confirmed with @astiob in pm (a libass maintainer).

**Comment by astiob** [comment]
Yeah, this is a known libass problem. Looks like we don’t have a GitHub issue for it in the most general case, the warning can be ignored when the font is immediately changed.

For drawings, though, https://github.com/libass/libass/issues/617 says that if the drawing nominally has the missing font, it will in fact fail to render if the font isn’t available. So: make sure your definition of “unused” doesn’t apply to drawings. That is, this is fine even though a spurious warning is printed:

```
Style: Sign,NoSuchFont,...
Dialogue: ...,Sign,...,{\fnAttachedFont\p1}m 0 0 l 100 100 100 0
```

but this needs to be fixed during authoring (until libass fixes the underlying issue, anyway):

```
Style: Sign,NoSuchFont,...
Dialogue: ...,Sign,...,{\p1}m 0 0 l 100 100 100 0{this still "uses" NoSuchFont even though it's a drawing}
```

**Comment by moi15moi** [comment]
The user can call fontcollector with the option ``--collect-draw-fonts`` to cover the issue you mentionned
