### ISSUE TITLE
[Feature] Add Logging

### ISSUE THREAD

**Issue by JySzE** [moi15moi/FontCollector#48]
Please add a logging parameter `--logging` `-log` .

Example:
```
--logging OUTPUT, -log OUTPUT
                        Destination path of log. If OUTPUT isn't specified, it will be the current path.
```

Helpful when doing large batches to easily search for any errors warnings etc.

You could just have its default log name be something like:

`<SYSTEMStartTime>_log.txt` 

Or something like that it really doesn't matter too much, Or just require the user to declare filename in OUTPUT with DIR.

Thanks!

**Comment by moi15moi** [comment]
@JySzE Does #54 suits your need?

**Comment by JySzE** [comment]
Works absolutely perfectly after last push, thank you.
