### ISSUE TITLE
Win95 Trad Chinese

### ISSUE THREAD

**Issue by kenmcd** [moi15moi/FontCollector#7]
Windows 95 OSR2.5 (Trad. Chinese)
https://archive.org/details/Win95CCHT
Extract ISO.
Find 3 .`cab` files - MINI.CAB, MINI1.CAB, MINI2.CAB (3-parts)
Use 7-Zip, or WinRAR, etc. to extract from MINI.CAB. 
You will find what you are looking for.

**Comment by moi15moi** [comment]
This has no link with this tool. https://github.com/MicrosoftDocs/typography-issues/issues/956

Thanks for the answer. Actually, I found the font and I reformulate my question.
